services:
  backend:
    image: jpyles0524/freeaskinternetapi:latest
    build:
      context: .
    container_name: searchbackend
    depends_on:
      - llm-freegpt35
    restart: on-failure
    networks:
      - search
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
    networks:
      - search
      # ollama:
      #   image: ollama/ollama:latest
      #   container_name: ollama
      #   pull_policy: always
      #   tty: true
      #   restart: always
      #   networks:
      #     - search
networks:
  search:
    external:
      name: search
