services:
  backend:
    # image: docker.io/nashsu/free_ask_internet:latest
    build:
      context: .
    container_name: searchbackend
    depends_on:
      - llm-freegpt35
    restart: on-failure
    # ports:
    #   - 8000:8000
    networks:
      - search

  llm-freegpt35:
    container_name: llm-freegpt35
    image: missuo/freegpt35:latest
    restart: always
    # ports:
    #   - 3040:3040

    networks:
      - search

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
    networks:
      - search

networks:
  search:
    external:
      name: search
